### ISSUE TITLE
localzation

### ISSUE THREAD

**Issue by MohamedMahmoud10** [gitsindonesia/gits_cli#17]
i have already my gen files localzation from intl_utils
how can i disable gits_cli from generate localztion files

**Comment by dena-gits** [comment]
hi @MohamedMahmoud10 we have a rebrand for this gits_cli to morpheme_cli and this issue has already fixing in morpheme_cli. you can try and check you can call flag `--no-l10n` in your args command
https://morphemedesign.github.io/morpheme-flutter-documentation/
https://pub.dev/packages/morpheme_cli
