### ISSUE TITLE
Need update to support flutter last version

### ISSUE THREAD

**Issue by the-best-is-best** [gitsindonesia/gits_cli#18]
Synchronous waiting using dart:cli waitFor and C API Dart_WaitForEvent is deprecated and disabled by default. This feature will be fully removed in Dart 3.4 release. You can currently still enable it by passing --enable_deprecated_wait_for to the Dart VM. See https://dartbug.com/52121.

**Comment by dena-gits** [comment]
Yes, we have noted this internally. because we have a dependency on the Dcli package and that doesn't completely solve the problem. I hope I can fix it as soon as possible.

**Comment by dena-gits** [comment]
hi @the-best-is-best  we have a rebrand for this gits_cli to morpheme_cli and this issue has already fixing in morpheme_cli. you can try and check
https://morphemedesign.github.io/morpheme-flutter-documentation/
https://pub.dev/packages/morpheme_cli

**Comment by dena-gits** [comment]
now this issue can be closed
